# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PythonProject\stickyMarkdown\GUI\notePreview.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotePreview(object):
    def setupUi(self, NotePreview):
        NotePreview.setObjectName("NotePreview")
        NotePreview.resize(340, 140)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NotePreview.sizePolicy().hasHeightForWidth())
        NotePreview.setSizePolicy(sizePolicy)
        NotePreview.setMinimumSize(QtCore.QSize(340, 140))
        NotePreview.setAutoFillBackground(False)
        NotePreview.setStyleSheet("QWidget#NotePreview{\n"
"    background-color:     #FAF0C8;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(NotePreview)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeLabel = QtWidgets.QLabel(NotePreview)
        self.timeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout.addWidget(self.timeLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(NotePreview)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(NotePreview)
        QtCore.QMetaObject.connectSlotsByName(NotePreview)

    def retranslateUi(self, NotePreview):
        _translate = QtCore.QCoreApplication.translate
        NotePreview.setWindowTitle(_translate("NotePreview", "Form"))
        self.timeLabel.setText(_translate("NotePreview", "Data/time"))
