# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PythonProject\stickyMarkdown\GUI\note.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Note(object):
    def setupUi(self, Note):
        Note.setObjectName("Note")
        Note.resize(805, 710)
        Note.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Note)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Note)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QFrame{\n"
"    background: #f0f000;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newNoteButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newNoteButton.sizePolicy().hasHeightForWidth())
        self.newNoteButton.setSizePolicy(sizePolicy)
        self.newNoteButton.setMaximumSize(QtCore.QSize(35, 35))
        self.newNoteButton.setStyleSheet("QPushButton:hover:!pressed{\n"
"    border: 1px solid #000000;\n"
"}")
        self.newNoteButton.setText("")
        self.newNoteButton.setIconSize(QtCore.QSize(20, 20))
        self.newNoteButton.setFlat(True)
        self.newNoteButton.setObjectName("newNoteButton")
        self.horizontalLayout.addWidget(self.newNoteButton)
        self.pinButton = QtWidgets.QPushButton(self.frame)
        self.pinButton.setMaximumSize(QtCore.QSize(35, 35))
        self.pinButton.setStyleSheet("QPushButton:hover:!pressed{\n"
"    border: 1px solid #000000;\n"
"}")
        self.pinButton.setText("")
        self.pinButton.setIconSize(QtCore.QSize(20, 20))
        self.pinButton.setFlat(True)
        self.pinButton.setObjectName("pinButton")
        self.horizontalLayout.addWidget(self.pinButton)
        self.editButton = QtWidgets.QPushButton(self.frame)
        self.editButton.setStyleSheet("QPushButton:hover:!pressed{\n"
"    border: 1px solid #000000;\n"
"}")
        self.editButton.setText("")
        self.editButton.setIconSize(QtCore.QSize(20, 20))
        self.editButton.setFlat(True)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.minimizeButton = QtWidgets.QPushButton(self.frame)
        self.minimizeButton.setMaximumSize(QtCore.QSize(35, 35))
        self.minimizeButton.setStyleSheet("QPushButton:hover:!pressed{\n"
"    border: 1px solid #000000;\n"
"}")
        self.minimizeButton.setText("")
        self.minimizeButton.setIconSize(QtCore.QSize(20, 20))
        self.minimizeButton.setCheckable(False)
        self.minimizeButton.setFlat(True)
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setMaximumSize(QtCore.QSize(35, 35))
        self.closeButton.setStyleSheet("QPushButton:hover:!pressed{\n"
"    border: 1px solid #000000;\n"
"}")
        self.closeButton.setText("")
        self.closeButton.setIconSize(QtCore.QSize(20, 20))
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Note)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(5, 0, 5, 5)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setStyleSheet("QSplitter::handle{\n"
"    border: 1px solid black;\n"
"}")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.editorLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.editorLayout.setContentsMargins(0, 0, 0, 0)
        self.editorLayout.setSpacing(0)
        self.editorLayout.setObjectName("editorLayout")
        self.editLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(12)
        self.editLabel.setFont(font)
        self.editLabel.setObjectName("editLabel")
        self.editorLayout.addWidget(self.editLabel)
        self.editor = MarkdownEditor(self.verticalLayoutWidget_2)
        self.editor.setStyleSheet("QTextEdit, QTextBrowser{\n"
"\n"
"border:1px solid #000000;\n"
"}")
        self.editor.setObjectName("editor")
        self.editorLayout.addWidget(self.editor)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.previewLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.previewLayout.setContentsMargins(0, 0, 0, 0)
        self.previewLayout.setSpacing(0)
        self.previewLayout.setObjectName("previewLayout")
        self.previewLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(12)
        self.previewLabel.setFont(font)
        self.previewLabel.setObjectName("previewLabel")
        self.previewLayout.addWidget(self.previewLabel)
        self.preview = MarkdownPreview(self.verticalLayoutWidget)
        self.preview.setStyleSheet("QTextEdit{\n"
"\n"
"border:1px solid #000000;\n"
"}")
        self.preview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.preview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.preview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.preview.setSearchPaths([])
        self.preview.setOpenExternalLinks(True)
        self.preview.setObjectName("preview")
        self.previewLayout.addWidget(self.preview)
        self.horizontalLayout_4.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Note)
        QtCore.QMetaObject.connectSlotsByName(Note)

    def retranslateUi(self, Note):
        _translate = QtCore.QCoreApplication.translate
        Note.setWindowTitle(_translate("Note", "Form"))
        self.editLabel.setText(_translate("Note", "Edit Markdown"))
        self.previewLabel.setText(_translate("Note", "Preview"))
from markdownEditor import MarkdownEditor, MarkdownPreview


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Note = QtWidgets.QWidget()
    ui = Ui_Note()
    ui.setupUi(Note)
    Note.show()
    sys.exit(app.exec_())
